service: sheet-flow-lambda

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  stage: ${opt:stage, "dev"}
  environment:
    S3BUCKET: heydu-${self:provider.stage}
    REGION: ${self:provider.region}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutBucketNotification
            - s3:GetBucketNotification
          Resource:
            - arn:aws:s3:::heydu-${self:provider.stage}/*
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutBucketNotification
            - s3:GetBucketNotification
          Resource:
            - arn:aws:s3:::heydu-${self:provider.stage}/*
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:Query
          Resource:
            - arn:aws:dynamodb:${self:provider.region}:*:table/heydu-batch-${self:provider.stage}
            - arn:aws:dynamodb:${self:provider.region}:*:table/heydu-user-${self:provider.stage}

functions:
  s3Handler:
    timeout: 120
    memorySize: 2048
    handler: functions/s3Handler.s3Handler
    events:
      - s3:
          bucket: heydu-${self:provider.stage}
          event: s3:ObjectCreated:*
          existing: true
          rules:
            # - prefix: my-folder/
            - suffix: .xlsx

plugins:
  - serverless-offline
