const { OTPSchema, ValidateOTPSchema } = require('./otp');
const {
	DegreeSchema,
	InstitutionTypeSchema,
	ProfileTypeSchema,
	RoleSchema,
	CountrySchema,
} = require('./utility');
const {
	StaffSchema,
	EditStaffSchema,
	StudentSchema,
	EditStudentSchema,
	FollowerSchema,
	GetFollowersSchema,
	InstitutionSchema,
	UpdateInstitutionSchema,
	GetInstitutionsSchema,
} = require('./user');
const { DepartmentSchema, SpecialisationSchema } = require('./batch');
const {
	PostSchema,
	EditPostSchema,
	DeletePostSchema,
	GetPutObjectSignedUrlSchema,
	GetPostSchema,
	GetProfilePostSchema,
	LikePostSchema,
	GetLikedPostSchema,
	SavePostSchema,
	GetSavedPostSchema,
	PinPostSchema,
	GetPinnedPostSchema,
} = require('./post');

module.exports = {
	InstitutionSchema,
	UpdateInstitutionSchema,
	GetInstitutionsSchema,
	OTPSchema,
	ValidateOTPSchema,
	DegreeSchema,
	InstitutionTypeSchema,
	ProfileTypeSchema,
	RoleSchema,
	CountrySchema,
	StaffSchema,
	EditStaffSchema,
	StudentSchema,
	EditStudentSchema,
	FollowerSchema,
	GetFollowersSchema,
	DepartmentSchema,
	SpecialisationSchema,
	PostSchema,
	EditPostSchema,
	DeletePostSchema,
	GetPutObjectSignedUrlSchema,
	GetPostSchema,
	GetProfilePostSchema,
	LikePostSchema,
	GetLikedPostSchema,
	SavePostSchema,
	GetSavedPostSchema,
	PinPostSchema,
	GetPinnedPostSchema,
};
