const { OTPSchema, ValidateOTPSchema, RefreshTokenSchema } = require('./otp');
const {
	DegreeSchema,
	InstitutionTypeSchema,
	ProfileTypeSchema,
	RoleSchema,
	CountrySchema,
} = require('./utility');
const {
	StaffSchema,
	EditStaffSchema,
	StudentSchema,
	EditStudentSchema,
	FollowerSchema,
	GetFollowersFollowingsSchema,
	InstitutionSchema,
	UpdateInstitutionSchema,
	GetInstitutionsSchema,
	AdminSchema,
	GetProfileKeySignedUrlsSchema,
	GetStudentsByBatchIDSchema,
	GetPostUsersSchema,
	RegisterDeviceTokenSchema,
} = require('./user');
const {
	DepartmentSchema,
	SpecialisationSchema,
	BatchSchema,
	GetBatchSchema,
} = require('./batch');
const {
	PostSchema,
	EditPostSchema,
	DeletePostSchema,
	GetPutObjectSignedUrlSchema,
	GetPostSchema,
	GetProfilePostSchema,
	LikePostSchema,
	GetLikedPostSchema,
	SavePostSchema,
	GetSavedPostSchema,
	PinPostSchema,
	GetPinnedPostSchema,
	CommentSchema,
	GetCommentsSchema,
	UpdateCommentSchema,
} = require('./post');

module.exports = {
	InstitutionSchema,
	UpdateInstitutionSchema,
	GetInstitutionsSchema,
	OTPSchema,
	ValidateOTPSchema,
	DegreeSchema,
	InstitutionTypeSchema,
	ProfileTypeSchema,
	RoleSchema,
	CountrySchema,
	StaffSchema,
	EditStaffSchema,
	StudentSchema,
	EditStudentSchema,
	FollowerSchema,
	GetFollowersFollowingsSchema,
	DepartmentSchema,
	SpecialisationSchema,
	BatchSchema,
	GetBatchSchema,
	PostSchema,
	EditPostSchema,
	DeletePostSchema,
	GetPutObjectSignedUrlSchema,
	GetPostSchema,
	GetProfilePostSchema,
	LikePostSchema,
	GetLikedPostSchema,
	SavePostSchema,
	GetSavedPostSchema,
	PinPostSchema,
	GetPinnedPostSchema,
	AdminSchema,
	GetProfileKeySignedUrlsSchema,
	RefreshTokenSchema,
	CommentSchema,
	GetCommentsSchema,
	UpdateCommentSchema,
	GetStudentsByBatchIDSchema,
	GetPostUsersSchema,
	RegisterDeviceTokenSchema,
};
