const { OTPSchema, ValidateOTPSchema, RefreshTokenSchema } = require('./otp');
const {
	DegreeSchema,
	InstitutionTypeSchema,
	ProfileTypeSchema,
	RoleSchema,
	CountrySchema,
} = require('./utility');
const {
	StaffSchema,
	BulkStaffSchema,
	EditStaffSchema,
	StudentSchema,
	EditStudentSchema,
	FollowerSchema,
	GetFollowersFollowingsSchema,
	InstitutionSchema,
	UpdateInstitutionSchema,
	GetInstitutionsSchema,
	AdminSchema,
	GetProfileKeySignedUrlsSchema,
	GetStudentsByBatchIDSchema,
	GetPostUsersSchema,
	RegisterDeviceTokenSchema,
	GetNotificationsSchema,
} = require('./user');
const {
	DepartmentSchema,
	BulkDepartmentsSchema,
	SpecialisationSchema,
	BatchSchema,
	GetBatchSchema,
	DeleteBatchSchema,
	AdditionalStudentUploadSchema,
	AddCourseSchema,
	ClassMaterialPresignSchema,
	AddClassMaterialSchema,
	DeleteClassMaterialSchema,
	GetCourseSchema,
	GetClassMaterialSchema,
	GetClassMaterialScopeSchema,
} = require('./batch');
const {
	PostSchema,
	EditPostSchema,
	DeletePostSchema,
	GetPutObjectSignedUrlSchema,
	GetPostSchema,
	GetProfilePostSchema,
	LikePostSchema,
	GetLikedPostSchema,
	SavePostSchema,
	GetSavedPostSchema,
	PinPostSchema,
	GetPinnedPostSchema,
	CommentSchema,
	GetCommentsSchema,
	UpdateCommentSchema,
} = require('./post');

const {
	CrapSignupSchema,
	CrapQuestionsSchema,
	UpdateCrapQuestionsSchema,
	BuyCrapBulkReportSchema,
	AdminCrapBulkTokenSchema,
	CheckCrapBulkTokenEligibilitySchema,
	RedeemCrapBulkTokenSchema,
	DeactivateCrapBulkTokenSchema,
} = require('./crap');

module.exports = {
	InstitutionSchema,
	UpdateInstitutionSchema,
	GetInstitutionsSchema,
	OTPSchema,
	ValidateOTPSchema,
	DegreeSchema,
	InstitutionTypeSchema,
	ProfileTypeSchema,
	RoleSchema,
	CountrySchema,
	StaffSchema,
	BulkStaffSchema,
	EditStaffSchema,
	StudentSchema,
	EditStudentSchema,
	FollowerSchema,
	GetFollowersFollowingsSchema,
	DepartmentSchema,
	BulkDepartmentsSchema,
	SpecialisationSchema,
	BatchSchema,
	GetBatchSchema,
	DeleteBatchSchema,
	AdditionalStudentUploadSchema,
	AddCourseSchema,
	ClassMaterialPresignSchema,
	AddClassMaterialSchema,
	DeleteClassMaterialSchema,
	GetCourseSchema,
	GetClassMaterialSchema,
	GetClassMaterialScopeSchema,
	PostSchema,
	EditPostSchema,
	DeletePostSchema,
	GetPutObjectSignedUrlSchema,
	GetPostSchema,
	GetProfilePostSchema,
	LikePostSchema,
	GetLikedPostSchema,
	SavePostSchema,
	GetSavedPostSchema,
	PinPostSchema,
	GetPinnedPostSchema,
	AdminSchema,
	GetProfileKeySignedUrlsSchema,
	RefreshTokenSchema,
	CommentSchema,
	GetCommentsSchema,
	UpdateCommentSchema,
	GetStudentsByBatchIDSchema,
	GetPostUsersSchema,
	RegisterDeviceTokenSchema,
	GetNotificationsSchema,
	CrapSignupSchema,
	CrapQuestionsSchema,
	UpdateCrapQuestionsSchema,
	BuyCrapBulkReportSchema,
	AdminCrapBulkTokenSchema,
	CheckCrapBulkTokenEligibilitySchema,
	RedeemCrapBulkTokenSchema,
	DeactivateCrapBulkTokenSchema,
};
